In [21]:
import pandas as pd
import numpy as np

In [22]:
data = np.random.randn(4,3)

In [23]:
data

array([[ 0.37937844, -0.22599787, -0.88556911],
       [ 0.85904625,  0.7751752 ,  0.92660336],
       [-1.33907106, -0.69550843,  0.3405566 ],
       [ 0.01080559, -1.47559502,  1.29015911]])

In [24]:
dataFrame = pd.DataFrame(data)

In [25]:
dataFrame[0] # column olarak getiriyor row olarak getirmiyor

0    0.379378
1    0.859046
2   -1.339071
3    0.010806
Name: 0, dtype: float64

In [26]:
dataFrame # serilerin iki boyutlu hali

          0         1         2
0  0.379378 -0.225998 -0.885569
1  0.859046  0.775175  0.926603
2 -1.339071 -0.695508  0.340557
3  0.010806 -1.475595  1.290159

In [27]:
yeniDataFrame = pd.DataFrame(data,index=["Atil","Zeynep","Atlas","Mehmet"],columns = ["Maas","Yas","Calisma Verileri"])

In [28]:
yeniDataFrame["Yas"]

Atil     -0.225998
Zeynep    0.775175
Atlas    -0.695508
Mehmet   -1.475595
Name: Yas, dtype: float64

In [29]:
yeniDataFrame

            Maas       Yas  Calisma Verileri
Atil    0.379378 -0.225998         -0.885569
Zeynep  0.859046  0.775175          0.926603
Atlas  -1.339071 -0.695508          0.340557
Mehmet  0.010806 -1.475595          1.290159

In [30]:
yeniDataFrame[["Maas","Yas"]]

            Maas       Yas
Atil    0.379378 -0.225998
Zeynep  0.859046  0.775175
Atlas  -1.339071 -0.695508
Mehmet  0.010806 -1.475595

In [31]:
yeniDataFrame

            Maas       Yas  Calisma Verileri
Atil    0.379378 -0.225998         -0.885569
Zeynep  0.859046  0.775175          0.926603
Atlas  -1.339071 -0.695508          0.340557
Mehmet  0.010806 -1.475595          1.290159

In [32]:
yeniDataFrame.loc["Atil"] #rowlarda loc yazıyoruz çünkü öncelikle column arıyor

Maas                0.379378
Yas                -0.225998
Calisma Verileri   -0.885569
Name: Atil, dtype: float64

In [33]:
yeniDataFrame.iloc[1] # index sayısı

Maas                0.859046
Yas                 0.775175
Calisma Verileri    0.926603
Name: Zeynep, dtype: float64

In [35]:
yeniDataFrame

            Maas       Yas  Calisma Verileri
Atil    0.379378 -0.225998         -0.885569
Zeynep  0.859046  0.775175          0.926603
Atlas  -1.339071 -0.695508          0.340557
Mehmet  0.010806 -1.475595          1.290159

In [36]:
#yeni kolon eklemek istiyoruz. nasıl yapıcaz?

In [37]:
yeniDataFrame["Emeklilik Yasi"] = yeniDataFrame["Yas"] + yeniDataFrame["Yas"]

In [38]:
yeniDataFrame

            Maas       Yas  Calisma Verileri  Emeklilik Yasi
Atil    0.379378 -0.225998         -0.885569       -0.451996
Zeynep  0.859046  0.775175          0.926603        1.550350
Atlas  -1.339071 -0.695508          0.340557       -1.391017
Mehmet  0.010806 -1.475595          1.290159       -2.951190

In [39]:
yeniDataFrame.drop("Emeklilik Yasi",axis = 1)

            Maas       Yas  Calisma Verileri
Atil    0.379378 -0.225998         -0.885569
Zeynep  0.859046  0.775175          0.926603
Atlas  -1.339071 -0.695508          0.340557
Mehmet  0.010806 -1.475595          1.290159

In [43]:
yeniDataFrame.drop("Mehmet")

            Maas       Yas  Calisma Verileri  Emeklilik Yasi
Atil    0.379378 -0.225998         -0.885569       -0.451996
Zeynep  0.859046  0.775175          0.926603        1.550350
Atlas  -1.339071 -0.695508          0.340557       -1.391017

In [44]:
yeniDataFrame.drop("Emeklilik Yasi", axis = 1, inplace=True)

In [45]:
yeniDataFrame

            Maas       Yas  Calisma Verileri
Atil    0.379378 -0.225998         -0.885569
Zeynep  0.859046  0.775175          0.926603
Atlas  -1.339071 -0.695508          0.340557
Mehmet  0.010806 -1.475595          1.290159

In [48]:
yeniDataFrame.loc["Atil"]["Yas"]

np.float64(-0.2259978692596928)

In [49]:
yeniDataFrame.loc["Atil","Yas"]

np.float64(-0.2259978692596928)

In [50]:
yeniDataFrame

            Maas       Yas  Calisma Verileri
Atil    0.379378 -0.225998         -0.885569
Zeynep  0.859046  0.775175          0.926603
Atlas  -1.339071 -0.695508          0.340557
Mehmet  0.010806 -1.475595          1.290159

In [52]:
booleanFrame = yeniDataFrame < 0

In [53]:
booleanFrame

         Maas    Yas  Calisma Verileri
Atil    False   True              True
Zeynep  False  False             False
Atlas    True   True             False
Mehmet  False   True             False

In [54]:
yeniDataFrame[booleanFrame]

            Maas       Yas  Calisma Verileri
Atil         NaN -0.225998         -0.885569
Zeynep       NaN       NaN               NaN
Atlas  -1.339071 -0.695508               NaN
Mehmet       NaN -1.475595               NaN

In [55]:
yeniDataFrame[yeniDataFrame["Yas"] > 0]

            Maas       Yas  Calisma Verileri
Zeynep  0.859046  0.775175          0.926603

In [56]:
yeniDataFrame

            Maas       Yas  Calisma Verileri
Atil    0.379378 -0.225998         -0.885569
Zeynep  0.859046  0.775175          0.926603
Atlas  -1.339071 -0.695508          0.340557
Mehmet  0.010806 -1.475595          1.290159

In [57]:
yeniDataFrame.reset_index()

    index      Maas       Yas  Calisma Verileri
0    Atil  0.379378 -0.225998         -0.885569
1  Zeynep  0.859046  0.775175          0.926603
2   Atlas -1.339071 -0.695508          0.340557
3  Mehmet  0.010806 -1.475595          1.290159

In [61]:
yeniIndeksListesi = ["Ati","Zey","Atl","Meh"]

In [63]:
yeniDataFrame.set_index["Yeni Indeks",inplace = True]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1032892070.py, line 1)

In [64]:
ilkIndeksler = ["Simpson","Simpson","Simpson","SouthPark","SouthPark","SouthPark"]

In [69]:
IcIndeksler = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [70]:
birlesmisIndeks = list(zip(ilkIndeksler,IcIndeksler))

In [72]:
birlesmisIndex = pd.MultiIndex.from_tuples(birlesmisIndeks)

In [73]:
birlesmisIndex

MultiIndex([(  'Simpson',   'Homer'),
            (  'Simpson',    'Bart'),
            (  'Simpson',   'Marge'),
            ('SouthPark', 'Cartman'),
            ('SouthPark',   'Kenny'),
            ('SouthPark',    'Kyle')],
           )

In [82]:
benimCizgiFilmListem = [[40,"A"],[10,"B"],[30,"C"],[9,"D"],[10,"E"],[11,"F"]]

In [85]:
cizgiFilmNumpyDizisi = np.array(benimCizgiFilmListem)

In [86]:
cizgiFilmDataFrame = pd.DataFrame(cizgiFilmNumpyDizsi, index=birlesmisIndeks,columns=["Yas","Meslek"])

NameError: name 'cizgiFilmNumpyDizsi' is not defined