In [1]:
import pandas as pd
import numpy as np

In [2]:
sozlukVerisi = {"Istanbul" : [30,29,np.nan],"Ankara" : [20,np.nan,25],"Izmir": [40,39,38]}
havaDurumuDataFrame = pd.DataFrame(sozlukVerisi)

In [3]:
havaDurumuDataFrame

   Istanbul  Ankara  Izmir
0      30.0    20.0     40
1      29.0     NaN     39
2       NaN    25.0     38

In [4]:
havaDurumuDataFrame.dropna() # NAN varsa komple çıkartır.

   Istanbul  Ankara  Izmir
0      30.0    20.0     40

In [6]:
yeniVeri = {"Istanbul" : [30,29,np.nan],"Ankara" : [20,np.nan,25],"Izmir" : [40,39,38],"Antalya":[45,np.nan,np.nan]}
yeniDataFrame = pd.DataFrame(yeniVeri)

In [7]:
yeniDataFrame

   Istanbul  Ankara  Izmir  Antalya
0      30.0    20.0     40     45.0
1      29.0     NaN     39      NaN
2       NaN    25.0     38      NaN

In [8]:
yeniDataFrame.dropna(axis=1,thresh=2) # axisi belirleyip iki tane olanları atar

   Istanbul  Ankara  Izmir
0      30.0    20.0     40
1      29.0     NaN     39
2       NaN    25.0     38

In [9]:
yeniDataFrame

   Istanbul  Ankara  Izmir  Antalya
0      30.0    20.0     40     45.0
1      29.0     NaN     39      NaN
2       NaN    25.0     38      NaN

In [10]:
yeniDataFrame.fillna(20) # boş olanların hepsini doldurmak için.

   Istanbul  Ankara  Izmir  Antalya
0      30.0    20.0     40     45.0
1      29.0    20.0     39     20.0
2      20.0    25.0     38     20.0

## groupby

In [11]:
# rowlarımızı sıralarımızı grupluyor. 
# multi indeksler gibi illa multi index olmasıa gerek yok.

In [14]:
maasSozlugu = {"Departman": ["Yazilim","Satis","Pazarlama","Finans","İnsan Kaynaklari","Hukuk"],
               "Çalışan İsimi" : ["Ahmet","Mehmet","Atil","Burak","Zeynep","Fatma"],
               "Maas" : [100,150,200,300,400,500]
              }

In [15]:
maasDataFrame = pd.DataFrame(maasSozlugu)

In [16]:
maasDataFrame

          Departman Çalışan İsimi  Maas
0           Yazilim         Ahmet   100
1             Satis        Mehmet   150
2         Pazarlama          Atil   200
3            Finans         Burak   300
4  İnsan Kaynaklari        Zeynep   400
5             Hukuk         Fatma   500

In [18]:
grupObjesi = maasDataFrame.groupby("Departman")

In [19]:
grupObjesi.count()

                  Çalışan İsimi  Maas
Departman
Finans                        1     1
Hukuk                         1     1
Pazarlama                     1     1
Satis                         1     1
Yazilim                       1     1
İnsan Kaynaklari              1     1

In [21]:
grupObjesi.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [22]:
grupObjesi.max

In [23]:
grupObjesi.min

In [24]:
grupObjesi.describe()

                  Maas
                 count   mean std    min    25%    50%    75%    max
Departman
Finans             1.0  300.0 NaN  300.0  300.0  300.0  300.0  300.0
Hukuk              1.0  500.0 NaN  500.0  500.0  500.0  500.0  500.0
Pazarlama          1.0  200.0 NaN  200.0  200.0  200.0  200.0  200.0
Satis              1.0  150.0 NaN  150.0  150.0  150.0  150.0  150.0
Yazilim            1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0
İnsan Kaynaklari   1.0  400.0 NaN  400.0  400.0  400.0  400.0  400.0