In [1]:
import numpy as np
import pandas as pd

In [4]:
sozluk1 = {"Isim" : ["Ahmet,"Mehmet","Zeynep","Atıl"],"Spor" : ["Koşu","Yüzme","Koşu","Baskebol"],"Kalori" : [100,200,300,400]}

SyntaxError: unterminated string literal (detected at line 1) (697021957.py, line 1)

In [5]:
## Concatenation # birleştirmek

In [6]:
pd.concat([dataFrame1,dataFrame2,dataFrame3])

NameError: name 'dataFrame1' is not defined

In [7]:
## merger

In [20]:
mergeSozluk1 = {"İsim" : ["Ahmet","Mehmet","Zeynep","Atıl"],
                "Spor" : ["Koşu","Yüzme","Koşu","Basketbol"]
               }

In [21]:
mergeDataFrame1 = pd.DataFrame(mergeSozluk1)

In [22]:
mergeDataFrame1

     İsim       Spor
0   Ahmet       Koşu
1  Mehmet      Yüzme
2  Zeynep       Koşu
3    Atıl  Basketbol

In [23]:
mergeSozluk2 = {"İsim" : ["Ahmet","Mehmet","Zeynep","Atıl"],
               "Kalori": [100,200,150,250]
               }

In [24]:
mergeDataFrame2 = pd.DataFrame(mergeSozluk2)

In [25]:
mergeDataFrame2

     İsim  Kalori
0   Ahmet     100
1  Mehmet     200
2  Zeynep     150
3    Atıl     250

In [26]:
pd.merge(mergeDataFrame1,mergeDataFrame2,on="İsim")

     İsim       Spor  Kalori
0   Ahmet       Koşu     100
1  Mehmet      Yüzme     200
2  Zeynep       Koşu     150
3    Atıl  Basketbol     250

In [27]:
maasSozluk = {"Isim" : ["Atil","Zeynep","Mehmet","Ahmet"],
             "Departman" : ["Yazilim","Satis","Pazarlama","Yazilim"],
             "Maas" : [200,300,400,500]
             }

In [28]:
maasDataFrame = pd.DataFrame(maasSozluk)

In [29]:
maasDataFrame

     Isim  Departman  Maas
0    Atil    Yazilim   200
1  Zeynep      Satis   300
2  Mehmet  Pazarlama   400
3   Ahmet    Yazilim   500

In [31]:
maasDataFrame["Departman"].unique()

array(['Yazilim', 'Satis', 'Pazarlama'], dtype=object)

In [33]:
maasDataFrame["Departman"].value_counts()

Departman
Yazilim      2
Satis        1
Pazarlama    1
Name: count, dtype: int64

In [34]:
maasDataFrame["Departman"].nunique()

3

In [43]:
def bruttenNete(maas):
    return maas * 0.66

In [44]:
maasDataFrame["Maas"].apply(bruttenNete)

0    132.0
1    198.0
2    264.0
3    330.0
Name: Maas, dtype: float64

In [45]:
maasDataFrame.isnull()

    Isim  Departman   Maas
0  False      False  False
1  False      False  False
2  False      False  False
3  False      False  False

In [53]:
yeniBirVeri = {"Karakter Sınıfı" : ["South Park","South Park","Simpson","Simpson"],
               "Karakter Ismi" : ["Cartman","Kenny","Homer","Bart"],
               "Karaktar Yas" : [9,10,50,20]
              }

In [54]:
karakterDF = pd.DataFrame(yeniBirVeri)

In [55]:
karakterDF

  Karakter Sınıfı Karakter Ismi  Karaktar Yas
0      South Park       Cartman             9
1      South Park         Kenny            10
2         Simpson         Homer            50
3         Simpson          Bart            20

In [56]:
karakterDF.pivot_table(values = "Karakter Yas", index = ["Karakter Sınıfı", "Karakter Ismi"])

KeyError: 'Karakter Yas'